//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Ep1Model", "fk_gate_status", "gate_status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.gate_status), "gate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.gate), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "item_fk", "item_type", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.item_type), "item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.item), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "fk_overlay_type", "overlay_type", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.overlay_type), "overlay", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.overlay), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "fk_restaurant_status", "restaurants_status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.restaurants_status), "restaurant", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.restaurant), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "fk_restaurants", "restaurant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.restaurant), "restaurants_posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.restaurants_posts), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "fk_restaurants_status", "restaurants_status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.restaurants_status), "restaurants_posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.restaurants_posts), true)]
[assembly: EdmRelationshipAttribute("Ep1Model", "menu_item", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.menu), "item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.item))]
[assembly: EdmRelationshipAttribute("Ep1Model", "fk_gate", "gate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ep1Dao.gate), "gate_posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ep1Dao.gate_posts), true)]

#endregion

namespace Ep1Dao
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Ep1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Ep1Entities object using the connection string found in the 'Ep1Entities' section of the application configuration file.
        /// </summary>
        public Ep1Entities() : base("name=Ep1Entities", "Ep1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Ep1Entities object.
        /// </summary>
        public Ep1Entities(string connectionString) : base(connectionString, "Ep1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Ep1Entities object.
        /// </summary>
        public Ep1Entities(EntityConnection connection) : base(connection, "Ep1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gate> gates
        {
            get
            {
                if ((_gates == null))
                {
                    _gates = base.CreateObjectSet<gate>("gates");
                }
                return _gates;
            }
        }
        private ObjectSet<gate> _gates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gate_status> gate_status
        {
            get
            {
                if ((_gate_status == null))
                {
                    _gate_status = base.CreateObjectSet<gate_status>("gate_status");
                }
                return _gate_status;
            }
        }
        private ObjectSet<gate_status> _gate_status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<item> items
        {
            get
            {
                if ((_items == null))
                {
                    _items = base.CreateObjectSet<item>("items");
                }
                return _items;
            }
        }
        private ObjectSet<item> _items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<item_type> item_type
        {
            get
            {
                if ((_item_type == null))
                {
                    _item_type = base.CreateObjectSet<item_type>("item_type");
                }
                return _item_type;
            }
        }
        private ObjectSet<item_type> _item_type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menu> menus
        {
            get
            {
                if ((_menus == null))
                {
                    _menus = base.CreateObjectSet<menu>("menus");
                }
                return _menus;
            }
        }
        private ObjectSet<menu> _menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<overlay> overlays
        {
            get
            {
                if ((_overlays == null))
                {
                    _overlays = base.CreateObjectSet<overlay>("overlays");
                }
                return _overlays;
            }
        }
        private ObjectSet<overlay> _overlays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<overlay_type> overlay_type
        {
            get
            {
                if ((_overlay_type == null))
                {
                    _overlay_type = base.CreateObjectSet<overlay_type>("overlay_type");
                }
                return _overlay_type;
            }
        }
        private ObjectSet<overlay_type> _overlay_type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<restaurant> restaurants
        {
            get
            {
                if ((_restaurants == null))
                {
                    _restaurants = base.CreateObjectSet<restaurant>("restaurants");
                }
                return _restaurants;
            }
        }
        private ObjectSet<restaurant> _restaurants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<restaurants_posts> restaurants_posts
        {
            get
            {
                if ((_restaurants_posts == null))
                {
                    _restaurants_posts = base.CreateObjectSet<restaurants_posts>("restaurants_posts");
                }
                return _restaurants_posts;
            }
        }
        private ObjectSet<restaurants_posts> _restaurants_posts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<restaurants_status> restaurants_status
        {
            get
            {
                if ((_restaurants_status == null))
                {
                    _restaurants_status = base.CreateObjectSet<restaurants_status>("restaurants_status");
                }
                return _restaurants_status;
            }
        }
        private ObjectSet<restaurants_status> _restaurants_status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<setting> settings
        {
            get
            {
                if ((_settings == null))
                {
                    _settings = base.CreateObjectSet<setting>("settings");
                }
                return _settings;
            }
        }
        private ObjectSet<setting> _settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gate_posts> gate_posts
        {
            get
            {
                if ((_gate_posts == null))
                {
                    _gate_posts = base.CreateObjectSet<gate_posts>("gate_posts");
                }
                return _gate_posts;
            }
        }
        private ObjectSet<gate_posts> _gate_posts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogates(gate gate)
        {
            base.AddObject("gates", gate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gate_status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogate_status(gate_status gate_status)
        {
            base.AddObject("gate_status", gate_status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToitems(item item)
        {
            base.AddObject("items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the item_type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToitem_type(item_type item_type)
        {
            base.AddObject("item_type", item_type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenus(menu menu)
        {
            base.AddObject("menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the overlays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTooverlays(overlay overlay)
        {
            base.AddObject("overlays", overlay);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the overlay_type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTooverlay_type(overlay_type overlay_type)
        {
            base.AddObject("overlay_type", overlay_type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the restaurants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorestaurants(restaurant restaurant)
        {
            base.AddObject("restaurants", restaurant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the restaurants_posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorestaurants_posts(restaurants_posts restaurants_posts)
        {
            base.AddObject("restaurants_posts", restaurants_posts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the restaurants_status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorestaurants_status(restaurants_status restaurants_status)
        {
            base.AddObject("restaurants_status", restaurants_status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosettings(setting setting)
        {
            base.AddObject("settings", setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gate_posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogate_posts(gate_posts gate_posts)
        {
            base.AddObject("gate_posts", gate_posts);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="gate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gate object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="latitude">Initial value of the latitude property.</param>
        /// <param name="longitude">Initial value of the longitude property.</param>
        public static gate Creategate(global::System.Int32 id, global::System.String name, global::System.Int32 status_id, global::System.Int32 latitude, global::System.Int32 longitude)
        {
            gate gate = new gate();
            gate.id = id;
            gate.name = name;
            gate.status_id = status_id;
            gate.latitude = latitude;
            gate.longitude = longitude;
            return gate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private global::System.Int32 _latitude;
        partial void OnlatitudeChanging(global::System.Int32 value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                OnlongitudeChanging(value);
                ReportPropertyChanging("longitude");
                _longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longitude");
                OnlongitudeChanged();
            }
        }
        private global::System.Int32 _longitude;
        partial void OnlongitudeChanging(global::System.Int32 value);
        partial void OnlongitudeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_gate_status", "gate_status")]
        public gate_status gate_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate_status>("Ep1Model.fk_gate_status", "gate_status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate_status>("Ep1Model.fk_gate_status", "gate_status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gate_status> gate_statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate_status>("Ep1Model.fk_gate_status", "gate_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gate_status>("Ep1Model.fk_gate_status", "gate_status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_gate", "gate_posts")]
        public EntityCollection<gate_posts> gate_posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gate_posts>("Ep1Model.fk_gate", "gate_posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gate_posts>("Ep1Model.fk_gate", "gate_posts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="gate_posts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gate_posts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gate_posts object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="gate_id">Initial value of the gate_id property.</param>
        /// <param name="distance">Initial value of the distance property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static gate_posts Creategate_posts(global::System.Int32 id, global::System.Int32 gate_id, global::System.Double distance, global::System.DateTime date)
        {
            gate_posts gate_posts = new gate_posts();
            gate_posts.id = id;
            gate_posts.gate_id = gate_id;
            gate_posts.distance = distance;
            gate_posts.date = date;
            return gate_posts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gate_id
        {
            get
            {
                return _gate_id;
            }
            set
            {
                Ongate_idChanging(value);
                ReportPropertyChanging("gate_id");
                _gate_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gate_id");
                Ongate_idChanged();
            }
        }
        private global::System.Int32 _gate_id;
        partial void Ongate_idChanging(global::System.Int32 value);
        partial void Ongate_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double distance
        {
            get
            {
                return _distance;
            }
            set
            {
                OndistanceChanging(value);
                ReportPropertyChanging("distance");
                _distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("distance");
                OndistanceChanged();
            }
        }
        private global::System.Double _distance;
        partial void OndistanceChanging(global::System.Double value);
        partial void OndistanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_gate", "gate")]
        public gate gate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate>("Ep1Model.fk_gate", "gate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate>("Ep1Model.fk_gate", "gate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gate> gateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gate>("Ep1Model.fk_gate", "gate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gate>("Ep1Model.fk_gate", "gate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="gate_status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gate_status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gate_status object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static gate_status Creategate_status(global::System.Int32 id, global::System.String name)
        {
            gate_status gate_status = new gate_status();
            gate_status.id = id;
            gate_status.name = name;
            return gate_status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_gate_status", "gate")]
        public EntityCollection<gate> gates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gate>("Ep1Model.fk_gate_status", "gate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gate>("Ep1Model.fk_gate_status", "gate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new item object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        public static item Createitem(global::System.Int32 id, global::System.String name, global::System.Int32 type)
        {
            item item = new item();
            item.id = id;
            item.name = name;
            item.type = type;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int32 _type;
        partial void OntypeChanging(global::System.Int32 value);
        partial void OntypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "item_fk", "item_type")]
        public item_type item_type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item_type>("Ep1Model.item_fk", "item_type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item_type>("Ep1Model.item_fk", "item_type").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<item_type> item_typeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item_type>("Ep1Model.item_fk", "item_type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<item_type>("Ep1Model.item_fk", "item_type", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "menu_item", "menu")]
        public EntityCollection<menu> menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<menu>("Ep1Model.menu_item", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<menu>("Ep1Model.menu_item", "menu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="item_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class item_type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new item_type object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static item_type Createitem_type(global::System.Int32 id, global::System.String name)
        {
            item_type item_type = new item_type();
            item_type.id = id;
            item_type.name = name;
            return item_type;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "item_fk", "item")]
        public EntityCollection<item> items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<item>("Ep1Model.item_fk", "item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<item>("Ep1Model.item_fk", "item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menu object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static menu Createmenu(global::System.Int32 id)
        {
            menu menu = new menu();
            menu.id = id;
            return menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "menu_item", "item")]
        public EntityCollection<item> items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<item>("Ep1Model.menu_item", "item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<item>("Ep1Model.menu_item", "item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="overlay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class overlay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new overlay object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="latitude">Initial value of the latitude property.</param>
        /// <param name="longitude">Initial value of the longitude property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="type_id">Initial value of the type_id property.</param>
        /// <param name="enable">Initial value of the enable property.</param>
        public static overlay Createoverlay(global::System.Int32 id, global::System.Int32 latitude, global::System.Int32 longitude, global::System.String name, global::System.Int32 type_id, global::System.Boolean enable)
        {
            overlay overlay = new overlay();
            overlay.id = id;
            overlay.latitude = latitude;
            overlay.longitude = longitude;
            overlay.name = name;
            overlay.type_id = type_id;
            overlay.enable = enable;
            return overlay;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private global::System.Int32 _latitude;
        partial void OnlatitudeChanging(global::System.Int32 value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                OnlongitudeChanging(value);
                ReportPropertyChanging("longitude");
                _longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longitude");
                OnlongitudeChanged();
            }
        }
        private global::System.Int32 _longitude;
        partial void OnlongitudeChanging(global::System.Int32 value);
        partial void OnlongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 type_id
        {
            get
            {
                return _type_id;
            }
            set
            {
                Ontype_idChanging(value);
                ReportPropertyChanging("type_id");
                _type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type_id");
                Ontype_idChanged();
            }
        }
        private global::System.Int32 _type_id;
        partial void Ontype_idChanging(global::System.Int32 value);
        partial void Ontype_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean enable
        {
            get
            {
                return _enable;
            }
            set
            {
                OnenableChanging(value);
                ReportPropertyChanging("enable");
                _enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enable");
                OnenableChanged();
            }
        }
        private global::System.Boolean _enable;
        partial void OnenableChanging(global::System.Boolean value);
        partial void OnenableChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_overlay_type", "overlay_type")]
        public overlay_type overlay_type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<overlay_type>("Ep1Model.fk_overlay_type", "overlay_type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<overlay_type>("Ep1Model.fk_overlay_type", "overlay_type").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<overlay_type> overlay_typeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<overlay_type>("Ep1Model.fk_overlay_type", "overlay_type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<overlay_type>("Ep1Model.fk_overlay_type", "overlay_type", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="overlay_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class overlay_type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new overlay_type object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static overlay_type Createoverlay_type(global::System.Int32 id, global::System.String name)
        {
            overlay_type overlay_type = new overlay_type();
            overlay_type.id = id;
            overlay_type.name = name;
            return overlay_type;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_overlay_type", "overlay")]
        public EntityCollection<overlay> overlays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<overlay>("Ep1Model.fk_overlay_type", "overlay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<overlay>("Ep1Model.fk_overlay_type", "overlay", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="restaurant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class restaurant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new restaurant object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        public static restaurant Createrestaurant(global::System.Int32 id, global::System.String name, global::System.Int32 status_id)
        {
            restaurant restaurant = new restaurant();
            restaurant.id = id;
            restaurant.name = name;
            restaurant.status_id = status_id;
            return restaurant;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clear_url
        {
            get
            {
                return _clear_url;
            }
            set
            {
                Onclear_urlChanging(value);
                ReportPropertyChanging("clear_url");
                _clear_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clear_url");
                Onclear_urlChanged();
            }
        }
        private global::System.String _clear_url;
        partial void Onclear_urlChanging(global::System.String value);
        partial void Onclear_urlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurant_status", "restaurants_status")]
        public restaurants_status restaurants_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurant_status", "restaurants_status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurant_status", "restaurants_status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<restaurants_status> restaurants_statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurant_status", "restaurants_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<restaurants_status>("Ep1Model.fk_restaurant_status", "restaurants_status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurants", "restaurants_posts")]
        public EntityCollection<restaurants_posts> restaurants_posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<restaurants_posts>("Ep1Model.fk_restaurants", "restaurants_posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<restaurants_posts>("Ep1Model.fk_restaurants", "restaurants_posts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="restaurants_posts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class restaurants_posts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new restaurants_posts object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="restaurant_id">Initial value of the restaurant_id property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static restaurants_posts Createrestaurants_posts(global::System.Int32 id, global::System.Int32 restaurant_id, global::System.Int32 status_id, global::System.DateTime date)
        {
            restaurants_posts restaurants_posts = new restaurants_posts();
            restaurants_posts.id = id;
            restaurants_posts.restaurant_id = restaurant_id;
            restaurants_posts.status_id = status_id;
            restaurants_posts.date = date;
            return restaurants_posts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 restaurant_id
        {
            get
            {
                return _restaurant_id;
            }
            set
            {
                Onrestaurant_idChanging(value);
                ReportPropertyChanging("restaurant_id");
                _restaurant_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("restaurant_id");
                Onrestaurant_idChanged();
            }
        }
        private global::System.Int32 _restaurant_id;
        partial void Onrestaurant_idChanging(global::System.Int32 value);
        partial void Onrestaurant_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurants", "restaurant")]
        public restaurant restaurant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurant>("Ep1Model.fk_restaurants", "restaurant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurant>("Ep1Model.fk_restaurants", "restaurant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<restaurant> restaurantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurant>("Ep1Model.fk_restaurants", "restaurant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<restaurant>("Ep1Model.fk_restaurants", "restaurant", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurants_status", "restaurants_status")]
        public restaurants_status restaurants_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurants_status", "restaurants_status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurants_status", "restaurants_status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<restaurants_status> restaurants_statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<restaurants_status>("Ep1Model.fk_restaurants_status", "restaurants_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<restaurants_status>("Ep1Model.fk_restaurants_status", "restaurants_status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="restaurants_status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class restaurants_status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new restaurants_status object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static restaurants_status Createrestaurants_status(global::System.Int32 id, global::System.String name)
        {
            restaurants_status restaurants_status = new restaurants_status();
            restaurants_status.id = id;
            restaurants_status.name = name;
            return restaurants_status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurant_status", "restaurant")]
        public EntityCollection<restaurant> restaurants
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<restaurant>("Ep1Model.fk_restaurant_status", "restaurant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<restaurant>("Ep1Model.fk_restaurant_status", "restaurant", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Ep1Model", "fk_restaurants_status", "restaurants_posts")]
        public EntityCollection<restaurants_posts> restaurants_posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<restaurants_posts>("Ep1Model.fk_restaurants_status", "restaurants_posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<restaurants_posts>("Ep1Model.fk_restaurants_status", "restaurants_posts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ep1Model", Name="setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new setting object.
        /// </summary>
        /// <param name="usp_latitude">Initial value of the usp_latitude property.</param>
        /// <param name="usp_longitude">Initial value of the usp_longitude property.</param>
        /// <param name="usp_gate1_latitude">Initial value of the usp_gate1_latitude property.</param>
        /// <param name="usp_gate1_longitude">Initial value of the usp_gate1_longitude property.</param>
        /// <param name="usp_gate2_latitude">Initial value of the usp_gate2_latitude property.</param>
        /// <param name="usp_gate2_longitude">Initial value of the usp_gate2_longitude property.</param>
        /// <param name="usp_gate3_latitude">Initial value of the usp_gate3_latitude property.</param>
        /// <param name="usp_gate3_longitude">Initial value of the usp_gate3_longitude property.</param>
        public static setting Createsetting(global::System.Int32 usp_latitude, global::System.Int32 usp_longitude, global::System.Int32 usp_gate1_latitude, global::System.Int32 usp_gate1_longitude, global::System.Int32 usp_gate2_latitude, global::System.Int32 usp_gate2_longitude, global::System.Int32 usp_gate3_latitude, global::System.Int32 usp_gate3_longitude)
        {
            setting setting = new setting();
            setting.usp_latitude = usp_latitude;
            setting.usp_longitude = usp_longitude;
            setting.usp_gate1_latitude = usp_gate1_latitude;
            setting.usp_gate1_longitude = usp_gate1_longitude;
            setting.usp_gate2_latitude = usp_gate2_latitude;
            setting.usp_gate2_longitude = usp_gate2_longitude;
            setting.usp_gate3_latitude = usp_gate3_latitude;
            setting.usp_gate3_longitude = usp_gate3_longitude;
            return setting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_latitude
        {
            get
            {
                return _usp_latitude;
            }
            set
            {
                if (_usp_latitude != value)
                {
                    Onusp_latitudeChanging(value);
                    ReportPropertyChanging("usp_latitude");
                    _usp_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_latitude");
                    Onusp_latitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_latitude;
        partial void Onusp_latitudeChanging(global::System.Int32 value);
        partial void Onusp_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_longitude
        {
            get
            {
                return _usp_longitude;
            }
            set
            {
                if (_usp_longitude != value)
                {
                    Onusp_longitudeChanging(value);
                    ReportPropertyChanging("usp_longitude");
                    _usp_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_longitude");
                    Onusp_longitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_longitude;
        partial void Onusp_longitudeChanging(global::System.Int32 value);
        partial void Onusp_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate1_latitude
        {
            get
            {
                return _usp_gate1_latitude;
            }
            set
            {
                if (_usp_gate1_latitude != value)
                {
                    Onusp_gate1_latitudeChanging(value);
                    ReportPropertyChanging("usp_gate1_latitude");
                    _usp_gate1_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate1_latitude");
                    Onusp_gate1_latitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate1_latitude;
        partial void Onusp_gate1_latitudeChanging(global::System.Int32 value);
        partial void Onusp_gate1_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate1_longitude
        {
            get
            {
                return _usp_gate1_longitude;
            }
            set
            {
                if (_usp_gate1_longitude != value)
                {
                    Onusp_gate1_longitudeChanging(value);
                    ReportPropertyChanging("usp_gate1_longitude");
                    _usp_gate1_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate1_longitude");
                    Onusp_gate1_longitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate1_longitude;
        partial void Onusp_gate1_longitudeChanging(global::System.Int32 value);
        partial void Onusp_gate1_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate2_latitude
        {
            get
            {
                return _usp_gate2_latitude;
            }
            set
            {
                if (_usp_gate2_latitude != value)
                {
                    Onusp_gate2_latitudeChanging(value);
                    ReportPropertyChanging("usp_gate2_latitude");
                    _usp_gate2_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate2_latitude");
                    Onusp_gate2_latitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate2_latitude;
        partial void Onusp_gate2_latitudeChanging(global::System.Int32 value);
        partial void Onusp_gate2_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate2_longitude
        {
            get
            {
                return _usp_gate2_longitude;
            }
            set
            {
                if (_usp_gate2_longitude != value)
                {
                    Onusp_gate2_longitudeChanging(value);
                    ReportPropertyChanging("usp_gate2_longitude");
                    _usp_gate2_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate2_longitude");
                    Onusp_gate2_longitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate2_longitude;
        partial void Onusp_gate2_longitudeChanging(global::System.Int32 value);
        partial void Onusp_gate2_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate3_latitude
        {
            get
            {
                return _usp_gate3_latitude;
            }
            set
            {
                if (_usp_gate3_latitude != value)
                {
                    Onusp_gate3_latitudeChanging(value);
                    ReportPropertyChanging("usp_gate3_latitude");
                    _usp_gate3_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate3_latitude");
                    Onusp_gate3_latitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate3_latitude;
        partial void Onusp_gate3_latitudeChanging(global::System.Int32 value);
        partial void Onusp_gate3_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usp_gate3_longitude
        {
            get
            {
                return _usp_gate3_longitude;
            }
            set
            {
                if (_usp_gate3_longitude != value)
                {
                    Onusp_gate3_longitudeChanging(value);
                    ReportPropertyChanging("usp_gate3_longitude");
                    _usp_gate3_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usp_gate3_longitude");
                    Onusp_gate3_longitudeChanged();
                }
            }
        }
        private global::System.Int32 _usp_gate3_longitude;
        partial void Onusp_gate3_longitudeChanging(global::System.Int32 value);
        partial void Onusp_gate3_longitudeChanged();

        #endregion
    
    }

    #endregion
    
}
